name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  publish-docker-hub:

    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - uses: actions/checkout@v4
    #- name: Build the Docker image
    #  run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with: 
        username: $ {{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and Push
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: itsjan/express-app:latest
